title: Robin Dueck Degen
description: Mathematics, projects, and project notes.
url: "https://robindueckdegen.com"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
permalink: /blog/:year/:month/:day/:title/
timezone: America/Regina

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

github_url: ""
